// Code generated by protoc-gen-go. DO NOT EDIT.
// source: harvesterinternalapi.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchItemUpdatesRequest struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchItemUpdatesRequest) Reset()         { *m = FetchItemUpdatesRequest{} }
func (m *FetchItemUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchItemUpdatesRequest) ProtoMessage()    {}
func (*FetchItemUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{0}
}

func (m *FetchItemUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemUpdatesRequest.Unmarshal(m, b)
}
func (m *FetchItemUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemUpdatesRequest.Marshal(b, m, deterministic)
}
func (m *FetchItemUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemUpdatesRequest.Merge(m, src)
}
func (m *FetchItemUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchItemUpdatesRequest.Size(m)
}
func (m *FetchItemUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemUpdatesRequest proto.InternalMessageInfo

func (m *FetchItemUpdatesRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type FetchItemUpdatesResponse struct {
	Items                []*UpdateItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FetchItemUpdatesResponse) Reset()         { *m = FetchItemUpdatesResponse{} }
func (m *FetchItemUpdatesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchItemUpdatesResponse) ProtoMessage()    {}
func (*FetchItemUpdatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{1}
}

func (m *FetchItemUpdatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemUpdatesResponse.Unmarshal(m, b)
}
func (m *FetchItemUpdatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemUpdatesResponse.Marshal(b, m, deterministic)
}
func (m *FetchItemUpdatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemUpdatesResponse.Merge(m, src)
}
func (m *FetchItemUpdatesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchItemUpdatesResponse.Size(m)
}
func (m *FetchItemUpdatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemUpdatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemUpdatesResponse proto.InternalMessageInfo

func (m *FetchItemUpdatesResponse) GetItems() []*UpdateItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type FetchItemTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchItemTypesRequest) Reset()         { *m = FetchItemTypesRequest{} }
func (m *FetchItemTypesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchItemTypesRequest) ProtoMessage()    {}
func (*FetchItemTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{2}
}

func (m *FetchItemTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemTypesRequest.Unmarshal(m, b)
}
func (m *FetchItemTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemTypesRequest.Marshal(b, m, deterministic)
}
func (m *FetchItemTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemTypesRequest.Merge(m, src)
}
func (m *FetchItemTypesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchItemTypesRequest.Size(m)
}
func (m *FetchItemTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemTypesRequest proto.InternalMessageInfo

type FetchItemTypesResponse struct {
	Types                []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchItemTypesResponse) Reset()         { *m = FetchItemTypesResponse{} }
func (m *FetchItemTypesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchItemTypesResponse) ProtoMessage()    {}
func (*FetchItemTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{3}
}

func (m *FetchItemTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemTypesResponse.Unmarshal(m, b)
}
func (m *FetchItemTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemTypesResponse.Marshal(b, m, deterministic)
}
func (m *FetchItemTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemTypesResponse.Merge(m, src)
}
func (m *FetchItemTypesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchItemTypesResponse.Size(m)
}
func (m *FetchItemTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemTypesResponse proto.InternalMessageInfo

func (m *FetchItemTypesResponse) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type UpdateItemIntervalRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Interval             int32    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemIntervalRequest) Reset()         { *m = UpdateItemIntervalRequest{} }
func (m *UpdateItemIntervalRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateItemIntervalRequest) ProtoMessage()    {}
func (*UpdateItemIntervalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{4}
}

func (m *UpdateItemIntervalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemIntervalRequest.Unmarshal(m, b)
}
func (m *UpdateItemIntervalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemIntervalRequest.Marshal(b, m, deterministic)
}
func (m *UpdateItemIntervalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemIntervalRequest.Merge(m, src)
}
func (m *UpdateItemIntervalRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateItemIntervalRequest.Size(m)
}
func (m *UpdateItemIntervalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemIntervalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemIntervalRequest proto.InternalMessageInfo

func (m *UpdateItemIntervalRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateItemIntervalRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *UpdateItemIntervalRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *UpdateItemIntervalRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type UpdateItemIntervalResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemIntervalResponse) Reset()         { *m = UpdateItemIntervalResponse{} }
func (m *UpdateItemIntervalResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateItemIntervalResponse) ProtoMessage()    {}
func (*UpdateItemIntervalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{5}
}

func (m *UpdateItemIntervalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemIntervalResponse.Unmarshal(m, b)
}
func (m *UpdateItemIntervalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemIntervalResponse.Marshal(b, m, deterministic)
}
func (m *UpdateItemIntervalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemIntervalResponse.Merge(m, src)
}
func (m *UpdateItemIntervalResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateItemIntervalResponse.Size(m)
}
func (m *UpdateItemIntervalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemIntervalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemIntervalResponse proto.InternalMessageInfo

func (m *UpdateItemIntervalResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateItemIntervalResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddItemRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Item                 string   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemRequest) Reset()         { *m = AddItemRequest{} }
func (m *AddItemRequest) String() string { return proto.CompactTextString(m) }
func (*AddItemRequest) ProtoMessage()    {}
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{6}
}

func (m *AddItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemRequest.Unmarshal(m, b)
}
func (m *AddItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemRequest.Marshal(b, m, deterministic)
}
func (m *AddItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemRequest.Merge(m, src)
}
func (m *AddItemRequest) XXX_Size() int {
	return xxx_messageInfo_AddItemRequest.Size(m)
}
func (m *AddItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemRequest proto.InternalMessageInfo

func (m *AddItemRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddItemRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type AddItemResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemResponse) Reset()         { *m = AddItemResponse{} }
func (m *AddItemResponse) String() string { return proto.CompactTextString(m) }
func (*AddItemResponse) ProtoMessage()    {}
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{7}
}

func (m *AddItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemResponse.Unmarshal(m, b)
}
func (m *AddItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemResponse.Marshal(b, m, deterministic)
}
func (m *AddItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemResponse.Merge(m, src)
}
func (m *AddItemResponse) XXX_Size() int {
	return xxx_messageInfo_AddItemResponse.Size(m)
}
func (m *AddItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemResponse proto.InternalMessageInfo

func (m *AddItemResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Interval             int32    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItem) Reset()         { *m = UpdateItem{} }
func (m *UpdateItem) String() string { return proto.CompactTextString(m) }
func (*UpdateItem) ProtoMessage()    {}
func (*UpdateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{8}
}

func (m *UpdateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItem.Unmarshal(m, b)
}
func (m *UpdateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItem.Marshal(b, m, deterministic)
}
func (m *UpdateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItem.Merge(m, src)
}
func (m *UpdateItem) XXX_Size() int {
	return xxx_messageInfo_UpdateItem.Size(m)
}
func (m *UpdateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItem.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItem proto.InternalMessageInfo

func (m *UpdateItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateItem) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *UpdateItem) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *UpdateItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type InsertSourceRequest struct {
	Source               *Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertSourceRequest) Reset()         { *m = InsertSourceRequest{} }
func (m *InsertSourceRequest) String() string { return proto.CompactTextString(m) }
func (*InsertSourceRequest) ProtoMessage()    {}
func (*InsertSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{9}
}

func (m *InsertSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertSourceRequest.Unmarshal(m, b)
}
func (m *InsertSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertSourceRequest.Marshal(b, m, deterministic)
}
func (m *InsertSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertSourceRequest.Merge(m, src)
}
func (m *InsertSourceRequest) XXX_Size() int {
	return xxx_messageInfo_InsertSourceRequest.Size(m)
}
func (m *InsertSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertSourceRequest proto.InternalMessageInfo

func (m *InsertSourceRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type InsertSourceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertSourceResponse) Reset()         { *m = InsertSourceResponse{} }
func (m *InsertSourceResponse) String() string { return proto.CompactTextString(m) }
func (*InsertSourceResponse) ProtoMessage()    {}
func (*InsertSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{10}
}

func (m *InsertSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertSourceResponse.Unmarshal(m, b)
}
func (m *InsertSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertSourceResponse.Marshal(b, m, deterministic)
}
func (m *InsertSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertSourceResponse.Merge(m, src)
}
func (m *InsertSourceResponse) XXX_Size() int {
	return xxx_messageInfo_InsertSourceResponse.Size(m)
}
func (m *InsertSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertSourceResponse proto.InternalMessageInfo

func (m *InsertSourceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateSourceRequest struct {
	Source               *Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceRequest) Reset()         { *m = UpdateSourceRequest{} }
func (m *UpdateSourceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceRequest) ProtoMessage()    {}
func (*UpdateSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{11}
}

func (m *UpdateSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceRequest.Unmarshal(m, b)
}
func (m *UpdateSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceRequest.Merge(m, src)
}
func (m *UpdateSourceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceRequest.Size(m)
}
func (m *UpdateSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceRequest proto.InternalMessageInfo

func (m *UpdateSourceRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type UpdateSourceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceResponse) Reset()         { *m = UpdateSourceResponse{} }
func (m *UpdateSourceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceResponse) ProtoMessage()    {}
func (*UpdateSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{12}
}

func (m *UpdateSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceResponse.Unmarshal(m, b)
}
func (m *UpdateSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceResponse.Merge(m, src)
}
func (m *UpdateSourceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceResponse.Size(m)
}
func (m *UpdateSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceResponse proto.InternalMessageInfo

func (m *UpdateSourceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateSourceSetRequest struct {
	SetKey               string   `protobuf:"bytes,2,opt,name=set_key,json=setKey,proto3" json:"set_key,omitempty"`
	ItemKeys             []string `protobuf:"bytes,3,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceSetRequest) Reset()         { *m = UpdateSourceSetRequest{} }
func (m *UpdateSourceSetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceSetRequest) ProtoMessage()    {}
func (*UpdateSourceSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{13}
}

func (m *UpdateSourceSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceSetRequest.Unmarshal(m, b)
}
func (m *UpdateSourceSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceSetRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSourceSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceSetRequest.Merge(m, src)
}
func (m *UpdateSourceSetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceSetRequest.Size(m)
}
func (m *UpdateSourceSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceSetRequest proto.InternalMessageInfo

func (m *UpdateSourceSetRequest) GetSetKey() string {
	if m != nil {
		return m.SetKey
	}
	return ""
}

func (m *UpdateSourceSetRequest) GetItemKeys() []string {
	if m != nil {
		return m.ItemKeys
	}
	return nil
}

type UpdateSourceSetResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceSetResponse) Reset()         { *m = UpdateSourceSetResponse{} }
func (m *UpdateSourceSetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceSetResponse) ProtoMessage()    {}
func (*UpdateSourceSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{14}
}

func (m *UpdateSourceSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceSetResponse.Unmarshal(m, b)
}
func (m *UpdateSourceSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceSetResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSourceSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceSetResponse.Merge(m, src)
}
func (m *UpdateSourceSetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceSetResponse.Size(m)
}
func (m *UpdateSourceSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceSetResponse proto.InternalMessageInfo

func (m *UpdateSourceSetResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FetchSourcesRequest struct {
	Priority             int32    `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourcesRequest) Reset()         { *m = FetchSourcesRequest{} }
func (m *FetchSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesRequest) ProtoMessage()    {}
func (*FetchSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{15}
}

func (m *FetchSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesRequest.Unmarshal(m, b)
}
func (m *FetchSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesRequest.Marshal(b, m, deterministic)
}
func (m *FetchSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesRequest.Merge(m, src)
}
func (m *FetchSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesRequest.Size(m)
}
func (m *FetchSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesRequest proto.InternalMessageInfo

func (m *FetchSourcesRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type FetchSourcesResponse struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FetchSourcesResponse) Reset()         { *m = FetchSourcesResponse{} }
func (m *FetchSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesResponse) ProtoMessage()    {}
func (*FetchSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{16}
}

func (m *FetchSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesResponse.Unmarshal(m, b)
}
func (m *FetchSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesResponse.Marshal(b, m, deterministic)
}
func (m *FetchSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesResponse.Merge(m, src)
}
func (m *FetchSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesResponse.Size(m)
}
func (m *FetchSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesResponse proto.InternalMessageInfo

func (m *FetchSourcesResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type FetchSourcesPaginationRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor               string   `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourcesPaginationRequest) Reset()         { *m = FetchSourcesPaginationRequest{} }
func (m *FetchSourcesPaginationRequest) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesPaginationRequest) ProtoMessage()    {}
func (*FetchSourcesPaginationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{17}
}

func (m *FetchSourcesPaginationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesPaginationRequest.Unmarshal(m, b)
}
func (m *FetchSourcesPaginationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesPaginationRequest.Marshal(b, m, deterministic)
}
func (m *FetchSourcesPaginationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesPaginationRequest.Merge(m, src)
}
func (m *FetchSourcesPaginationRequest) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesPaginationRequest.Size(m)
}
func (m *FetchSourcesPaginationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesPaginationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesPaginationRequest proto.InternalMessageInfo

func (m *FetchSourcesPaginationRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FetchSourcesPaginationRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FetchSourcesPaginationRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type FetchSourcesPaginationResponse struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Cursor               string    `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FetchSourcesPaginationResponse) Reset()         { *m = FetchSourcesPaginationResponse{} }
func (m *FetchSourcesPaginationResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesPaginationResponse) ProtoMessage()    {}
func (*FetchSourcesPaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{18}
}

func (m *FetchSourcesPaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesPaginationResponse.Unmarshal(m, b)
}
func (m *FetchSourcesPaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesPaginationResponse.Marshal(b, m, deterministic)
}
func (m *FetchSourcesPaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesPaginationResponse.Merge(m, src)
}
func (m *FetchSourcesPaginationResponse) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesPaginationResponse.Size(m)
}
func (m *FetchSourcesPaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesPaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesPaginationResponse proto.InternalMessageInfo

func (m *FetchSourcesPaginationResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *FetchSourcesPaginationResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type FetchSourceSetRequest struct {
	SetKey               string   `protobuf:"bytes,1,opt,name=set_key,json=setKey,proto3" json:"set_key,omitempty"`
	ItemKeys             []string `protobuf:"bytes,2,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourceSetRequest) Reset()         { *m = FetchSourceSetRequest{} }
func (m *FetchSourceSetRequest) String() string { return proto.CompactTextString(m) }
func (*FetchSourceSetRequest) ProtoMessage()    {}
func (*FetchSourceSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{19}
}

func (m *FetchSourceSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourceSetRequest.Unmarshal(m, b)
}
func (m *FetchSourceSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourceSetRequest.Marshal(b, m, deterministic)
}
func (m *FetchSourceSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourceSetRequest.Merge(m, src)
}
func (m *FetchSourceSetRequest) XXX_Size() int {
	return xxx_messageInfo_FetchSourceSetRequest.Size(m)
}
func (m *FetchSourceSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourceSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourceSetRequest proto.InternalMessageInfo

func (m *FetchSourceSetRequest) GetSetKey() string {
	if m != nil {
		return m.SetKey
	}
	return ""
}

func (m *FetchSourceSetRequest) GetItemKeys() []string {
	if m != nil {
		return m.ItemKeys
	}
	return nil
}

type FetchSourceSetResponse struct {
	ItemKeys             []string `protobuf:"bytes,1,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourceSetResponse) Reset()         { *m = FetchSourceSetResponse{} }
func (m *FetchSourceSetResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSourceSetResponse) ProtoMessage()    {}
func (*FetchSourceSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{20}
}

func (m *FetchSourceSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourceSetResponse.Unmarshal(m, b)
}
func (m *FetchSourceSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourceSetResponse.Marshal(b, m, deterministic)
}
func (m *FetchSourceSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourceSetResponse.Merge(m, src)
}
func (m *FetchSourceSetResponse) XXX_Size() int {
	return xxx_messageInfo_FetchSourceSetResponse.Size(m)
}
func (m *FetchSourceSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourceSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourceSetResponse proto.InternalMessageInfo

func (m *FetchSourceSetResponse) GetItemKeys() []string {
	if m != nil {
		return m.ItemKeys
	}
	return nil
}

type DeleteSourceRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSourceRequest) Reset()         { *m = DeleteSourceRequest{} }
func (m *DeleteSourceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSourceRequest) ProtoMessage()    {}
func (*DeleteSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{21}
}

func (m *DeleteSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSourceRequest.Unmarshal(m, b)
}
func (m *DeleteSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSourceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSourceRequest.Merge(m, src)
}
func (m *DeleteSourceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSourceRequest.Size(m)
}
func (m *DeleteSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSourceRequest proto.InternalMessageInfo

func (m *DeleteSourceRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteSourceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSourceResponse) Reset()         { *m = DeleteSourceResponse{} }
func (m *DeleteSourceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSourceResponse) ProtoMessage()    {}
func (*DeleteSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{22}
}

func (m *DeleteSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSourceResponse.Unmarshal(m, b)
}
func (m *DeleteSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSourceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSourceResponse.Merge(m, src)
}
func (m *DeleteSourceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSourceResponse.Size(m)
}
func (m *DeleteSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSourceResponse proto.InternalMessageInfo

func (m *DeleteSourceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type SearchSourcesRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Categories           []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSourcesRequest) Reset()         { *m = SearchSourcesRequest{} }
func (m *SearchSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchSourcesRequest) ProtoMessage()    {}
func (*SearchSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{23}
}

func (m *SearchSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSourcesRequest.Unmarshal(m, b)
}
func (m *SearchSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSourcesRequest.Marshal(b, m, deterministic)
}
func (m *SearchSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSourcesRequest.Merge(m, src)
}
func (m *SearchSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchSourcesRequest.Size(m)
}
func (m *SearchSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSourcesRequest proto.InternalMessageInfo

func (m *SearchSourcesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchSourcesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchSourcesRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchSourcesRequest) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

type SearchSourcesResponse struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchSourcesResponse) Reset()         { *m = SearchSourcesResponse{} }
func (m *SearchSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchSourcesResponse) ProtoMessage()    {}
func (*SearchSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{24}
}

func (m *SearchSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSourcesResponse.Unmarshal(m, b)
}
func (m *SearchSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSourcesResponse.Marshal(b, m, deterministic)
}
func (m *SearchSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSourcesResponse.Merge(m, src)
}
func (m *SearchSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchSourcesResponse.Size(m)
}
func (m *SearchSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSourcesResponse proto.InternalMessageInfo

func (m *SearchSourcesResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type Source struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority             int32    `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Format               string   `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	Categories           []string `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
	Lookedat             string   `protobuf:"bytes,9,opt,name=lookedat,proto3" json:"lookedat,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{25}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Source) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Source) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Source) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Source) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Source) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Source) GetLookedat() string {
	if m != nil {
		return m.Lookedat
	}
	return ""
}

func (m *Source) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FetchTagsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTagsRequest) Reset()         { *m = FetchTagsRequest{} }
func (m *FetchTagsRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTagsRequest) ProtoMessage()    {}
func (*FetchTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{26}
}

func (m *FetchTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTagsRequest.Unmarshal(m, b)
}
func (m *FetchTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTagsRequest.Marshal(b, m, deterministic)
}
func (m *FetchTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTagsRequest.Merge(m, src)
}
func (m *FetchTagsRequest) XXX_Size() int {
	return xxx_messageInfo_FetchTagsRequest.Size(m)
}
func (m *FetchTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTagsRequest proto.InternalMessageInfo

type FetchTagsResponse struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTagsResponse) Reset()         { *m = FetchTagsResponse{} }
func (m *FetchTagsResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTagsResponse) ProtoMessage()    {}
func (*FetchTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{27}
}

func (m *FetchTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTagsResponse.Unmarshal(m, b)
}
func (m *FetchTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTagsResponse.Marshal(b, m, deterministic)
}
func (m *FetchTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTagsResponse.Merge(m, src)
}
func (m *FetchTagsResponse) XXX_Size() int {
	return xxx_messageInfo_FetchTagsResponse.Size(m)
}
func (m *FetchTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTagsResponse proto.InternalMessageInfo

func (m *FetchTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type InsertTagRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTagRequest) Reset()         { *m = InsertTagRequest{} }
func (m *InsertTagRequest) String() string { return proto.CompactTextString(m) }
func (*InsertTagRequest) ProtoMessage()    {}
func (*InsertTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{28}
}

func (m *InsertTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTagRequest.Unmarshal(m, b)
}
func (m *InsertTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTagRequest.Marshal(b, m, deterministic)
}
func (m *InsertTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTagRequest.Merge(m, src)
}
func (m *InsertTagRequest) XXX_Size() int {
	return xxx_messageInfo_InsertTagRequest.Size(m)
}
func (m *InsertTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTagRequest proto.InternalMessageInfo

func (m *InsertTagRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type InsertTagResponse struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTagResponse) Reset()         { *m = InsertTagResponse{} }
func (m *InsertTagResponse) String() string { return proto.CompactTextString(m) }
func (*InsertTagResponse) ProtoMessage()    {}
func (*InsertTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{29}
}

func (m *InsertTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTagResponse.Unmarshal(m, b)
}
func (m *InsertTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTagResponse.Marshal(b, m, deterministic)
}
func (m *InsertTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTagResponse.Merge(m, src)
}
func (m *InsertTagResponse) XXX_Size() int {
	return xxx_messageInfo_InsertTagResponse.Size(m)
}
func (m *InsertTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTagResponse proto.InternalMessageInfo

func (m *InsertTagResponse) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type DeleteTagRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagRequest) Reset()         { *m = DeleteTagRequest{} }
func (m *DeleteTagRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagRequest) ProtoMessage()    {}
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{30}
}

func (m *DeleteTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagRequest.Unmarshal(m, b)
}
func (m *DeleteTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagRequest.Merge(m, src)
}
func (m *DeleteTagRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagRequest.Size(m)
}
func (m *DeleteTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagRequest proto.InternalMessageInfo

func (m *DeleteTagRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTagResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagResponse) Reset()         { *m = DeleteTagResponse{} }
func (m *DeleteTagResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTagResponse) ProtoMessage()    {}
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{31}
}

func (m *DeleteTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagResponse.Unmarshal(m, b)
}
func (m *DeleteTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagResponse.Merge(m, src)
}
func (m *DeleteTagResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTagResponse.Size(m)
}
func (m *DeleteTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagResponse proto.InternalMessageInfo

func (m *DeleteTagResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type SearchTagsRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagsRequest) Reset()         { *m = SearchTagsRequest{} }
func (m *SearchTagsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTagsRequest) ProtoMessage()    {}
func (*SearchTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{32}
}

func (m *SearchTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagsRequest.Unmarshal(m, b)
}
func (m *SearchTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagsRequest.Marshal(b, m, deterministic)
}
func (m *SearchTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagsRequest.Merge(m, src)
}
func (m *SearchTagsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTagsRequest.Size(m)
}
func (m *SearchTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagsRequest proto.InternalMessageInfo

func (m *SearchTagsRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type SearchTagsResponse struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagsResponse) Reset()         { *m = SearchTagsResponse{} }
func (m *SearchTagsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTagsResponse) ProtoMessage()    {}
func (*SearchTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{33}
}

func (m *SearchTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagsResponse.Unmarshal(m, b)
}
func (m *SearchTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagsResponse.Marshal(b, m, deterministic)
}
func (m *SearchTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagsResponse.Merge(m, src)
}
func (m *SearchTagsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTagsResponse.Size(m)
}
func (m *SearchTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagsResponse proto.InternalMessageInfo

func (m *SearchTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{34}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchItemUpdatesRequest)(nil), "api.FetchItemUpdatesRequest")
	proto.RegisterType((*FetchItemUpdatesResponse)(nil), "api.FetchItemUpdatesResponse")
	proto.RegisterType((*FetchItemTypesRequest)(nil), "api.FetchItemTypesRequest")
	proto.RegisterType((*FetchItemTypesResponse)(nil), "api.FetchItemTypesResponse")
	proto.RegisterType((*UpdateItemIntervalRequest)(nil), "api.UpdateItemIntervalRequest")
	proto.RegisterType((*UpdateItemIntervalResponse)(nil), "api.UpdateItemIntervalResponse")
	proto.RegisterType((*AddItemRequest)(nil), "api.AddItemRequest")
	proto.RegisterType((*AddItemResponse)(nil), "api.AddItemResponse")
	proto.RegisterType((*UpdateItem)(nil), "api.UpdateItem")
	proto.RegisterType((*InsertSourceRequest)(nil), "api.InsertSourceRequest")
	proto.RegisterType((*InsertSourceResponse)(nil), "api.InsertSourceResponse")
	proto.RegisterType((*UpdateSourceRequest)(nil), "api.UpdateSourceRequest")
	proto.RegisterType((*UpdateSourceResponse)(nil), "api.UpdateSourceResponse")
	proto.RegisterType((*UpdateSourceSetRequest)(nil), "api.UpdateSourceSetRequest")
	proto.RegisterType((*UpdateSourceSetResponse)(nil), "api.UpdateSourceSetResponse")
	proto.RegisterType((*FetchSourcesRequest)(nil), "api.FetchSourcesRequest")
	proto.RegisterType((*FetchSourcesResponse)(nil), "api.FetchSourcesResponse")
	proto.RegisterType((*FetchSourcesPaginationRequest)(nil), "api.FetchSourcesPaginationRequest")
	proto.RegisterType((*FetchSourcesPaginationResponse)(nil), "api.FetchSourcesPaginationResponse")
	proto.RegisterType((*FetchSourceSetRequest)(nil), "api.FetchSourceSetRequest")
	proto.RegisterType((*FetchSourceSetResponse)(nil), "api.FetchSourceSetResponse")
	proto.RegisterType((*DeleteSourceRequest)(nil), "api.DeleteSourceRequest")
	proto.RegisterType((*DeleteSourceResponse)(nil), "api.DeleteSourceResponse")
	proto.RegisterType((*SearchSourcesRequest)(nil), "api.SearchSourcesRequest")
	proto.RegisterType((*SearchSourcesResponse)(nil), "api.SearchSourcesResponse")
	proto.RegisterType((*Source)(nil), "api.Source")
	proto.RegisterType((*FetchTagsRequest)(nil), "api.FetchTagsRequest")
	proto.RegisterType((*FetchTagsResponse)(nil), "api.FetchTagsResponse")
	proto.RegisterType((*InsertTagRequest)(nil), "api.InsertTagRequest")
	proto.RegisterType((*InsertTagResponse)(nil), "api.InsertTagResponse")
	proto.RegisterType((*DeleteTagRequest)(nil), "api.DeleteTagRequest")
	proto.RegisterType((*DeleteTagResponse)(nil), "api.DeleteTagResponse")
	proto.RegisterType((*SearchTagsRequest)(nil), "api.SearchTagsRequest")
	proto.RegisterType((*SearchTagsResponse)(nil), "api.SearchTagsResponse")
	proto.RegisterType((*Tag)(nil), "api.Tag")
}

func init() { proto.RegisterFile("harvesterinternalapi.proto", fileDescriptor_956f1945bd8023db) }

var fileDescriptor_956f1945bd8023db = []byte{
	// 1063 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x7b, 0x6f, 0x1b, 0x45,
	0x10, 0xf7, 0xfb, 0x31, 0x81, 0x3c, 0xd6, 0x8e, 0x73, 0xbd, 0xa4, 0xa1, 0xda, 0xb6, 0x6a, 0x11,
	0x92, 0x51, 0x82, 0x40, 0xa8, 0x82, 0xa2, 0x54, 0x80, 0x1a, 0x45, 0x44, 0xc5, 0x09, 0xe2, 0xcf,
	0x6a, 0x6b, 0x2f, 0xd7, 0xa5, 0xbe, 0x07, 0xb7, 0xeb, 0x4a, 0xfe, 0x4a, 0x7c, 0x36, 0x3e, 0x04,
	0xda, 0xc7, 0xed, 0xed, 0x3d, 0x1c, 0x53, 0xa4, 0xfe, 0x77, 0x3b, 0x33, 0xbf, 0x79, 0xec, 0xcc,
	0xce, 0xcc, 0x81, 0xff, 0x96, 0xa4, 0xef, 0x29, 0x17, 0x34, 0x65, 0x91, 0xa0, 0x69, 0x44, 0x96,
	0x24, 0x61, 0xd3, 0x24, 0x8d, 0x45, 0x8c, 0xda, 0x24, 0x61, 0xf8, 0x0c, 0x8e, 0x7e, 0xa6, 0x62,
	0xfe, 0xf6, 0x52, 0xd0, 0xf0, 0xb7, 0x64, 0x41, 0x04, 0xe5, 0x33, 0xfa, 0xd7, 0x8a, 0x72, 0x81,
	0x26, 0xd0, 0x23, 0x61, 0xbc, 0x8a, 0x84, 0xd7, 0x7c, 0xd0, 0x7c, 0xda, 0x9d, 0x99, 0x13, 0xbe,
	0x00, 0xaf, 0x0a, 0xe1, 0x49, 0x1c, 0x71, 0x8a, 0x1e, 0x43, 0x97, 0x09, 0x1a, 0x72, 0xaf, 0xf9,
	0xa0, 0xfd, 0x74, 0xe7, 0x7c, 0x6f, 0x2a, 0xcd, 0x69, 0x21, 0x29, 0x3e, 0xd3, 0x5c, 0x7c, 0x04,
	0x87, 0x56, 0xc5, 0xed, 0x3a, 0xb1, 0x36, 0xf1, 0x14, 0x26, 0x65, 0x86, 0xd1, 0x3c, 0x86, 0xae,
	0x90, 0x04, 0xa5, 0x79, 0x38, 0xd3, 0x07, 0xbc, 0x86, 0x7b, 0xb9, 0xf6, 0x4b, 0x19, 0xe2, 0x7b,
	0xb2, 0xcc, 0x02, 0xd8, 0x85, 0x16, 0x5b, 0x28, 0xe7, 0x87, 0xb3, 0x16, 0x5b, 0x20, 0x1f, 0x06,
	0xcc, 0x88, 0x78, 0x2d, 0x15, 0x92, 0x3d, 0xa3, 0x13, 0x18, 0x0a, 0x16, 0x52, 0x2e, 0x48, 0x98,
	0x78, 0x6d, 0x05, 0xc9, 0x09, 0x08, 0x41, 0x47, 0xda, 0xf3, 0x3a, 0x8a, 0xa1, 0xbe, 0xf1, 0x35,
	0xf8, 0x75, 0xa6, 0x8d, 0xbb, 0x13, 0xe8, 0x71, 0x41, 0xc4, 0x8a, 0x67, 0x97, 0xa7, 0x4f, 0xc8,
	0x83, 0x7e, 0x48, 0x39, 0x27, 0x01, 0x55, 0x2e, 0x0c, 0x67, 0xd9, 0x11, 0x7f, 0x0b, 0xbb, 0x17,
	0x8b, 0x85, 0xba, 0x25, 0xe3, 0x7f, 0x66, 0xb5, 0x99, 0x5b, 0x95, 0x34, 0x79, 0x85, 0x06, 0xac,
	0xbe, 0xf1, 0xe7, 0xb0, 0x67, 0x91, 0x77, 0x9b, 0xc7, 0x7f, 0x02, 0xe4, 0x4e, 0x7f, 0xe4, 0x0b,
	0x7a, 0x06, 0xa3, 0xcb, 0x88, 0xd3, 0x54, 0xdc, 0xc4, 0xab, 0x74, 0x4e, 0xb3, 0xa8, 0x1e, 0x42,
	0x8f, 0x2b, 0x82, 0x32, 0xbc, 0x73, 0xbe, 0xa3, 0x6a, 0xc4, 0xc8, 0x18, 0x16, 0x9e, 0xc2, 0xb8,
	0x88, 0xdd, 0x12, 0xd7, 0x33, 0x18, 0xe9, 0xb8, 0xfe, 0x9f, 0xad, 0x22, 0x76, 0x8b, 0xad, 0x6b,
	0x98, 0xb8, 0xf2, 0x37, 0x54, 0x64, 0xe6, 0x8e, 0xa0, 0xcf, 0xa9, 0x78, 0xfd, 0x8e, 0xae, 0x4d,
	0x7e, 0x7a, 0x9c, 0x8a, 0x2b, 0xba, 0x46, 0xc7, 0x30, 0x94, 0x99, 0x92, 0x1c, 0xee, 0xb5, 0x55,
	0x01, 0x0f, 0x24, 0xe1, 0x8a, 0xae, 0xb9, 0x7c, 0x82, 0x15, 0x7d, 0x5b, 0x5c, 0x38, 0x83, 0x91,
	0x7a, 0x26, 0x1a, 0x61, 0x5f, 0xac, 0x0f, 0x83, 0x24, 0x65, 0x71, 0xca, 0xc4, 0xda, 0x00, 0xec,
	0x19, 0x7f, 0x0f, 0xe3, 0x22, 0xc4, 0xbe, 0xd8, 0xbe, 0xbe, 0x87, 0xec, 0xcd, 0x16, 0xee, 0x28,
	0xe3, 0x61, 0x02, 0xf7, 0x5d, 0xf8, 0x2b, 0x12, 0xb0, 0x88, 0x08, 0x16, 0x47, 0x77, 0x15, 0xeb,
	0x18, 0xba, 0x4b, 0x16, 0x32, 0x61, 0x8a, 0x49, 0x1f, 0x64, 0x50, 0xf3, 0x55, 0xca, 0xe3, 0xd4,
	0x94, 0x91, 0x39, 0xe1, 0xd7, 0x70, 0xba, 0xc9, 0xc4, 0x07, 0xf9, 0xea, 0x18, 0x68, 0x15, 0x0c,
	0xfc, 0x62, 0xba, 0xce, 0x5d, 0x79, 0x6b, 0x6e, 0xce, 0x5b, 0xab, 0x94, 0xb7, 0xaf, 0x4d, 0xaf,
	0xaa, 0xa6, 0xad, 0x00, 0x6b, 0x96, 0x60, 0x4f, 0x60, 0xf4, 0x23, 0x5d, 0xd2, 0x72, 0xa9, 0xee,
	0x43, 0x3b, 0xb7, 0x2f, 0x3f, 0x65, 0x5d, 0x16, 0x05, 0xb7, 0x14, 0x45, 0x02, 0xe3, 0x1b, 0x4a,
	0xd2, 0x4a, 0x55, 0x6c, 0x68, 0x23, 0x11, 0x09, 0xb3, 0x1e, 0xa4, 0xbe, 0xa5, 0x07, 0xab, 0x74,
	0x69, 0x92, 0x22, 0x3f, 0xd1, 0x29, 0xc0, 0x9c, 0x08, 0x1a, 0xc4, 0x29, 0xa3, 0xdc, 0xeb, 0xa8,
	0x40, 0x1c, 0x0a, 0x7e, 0x0e, 0x87, 0x25, 0x8b, 0x1f, 0x56, 0x54, 0xff, 0x34, 0xa1, 0xa7, 0x69,
	0xd5, 0xf0, 0x4d, 0x73, 0x6a, 0xd9, 0xe6, 0x94, 0xb9, 0xdc, 0x76, 0x5c, 0x76, 0x0b, 0xbe, 0x53,
	0x2c, 0x78, 0x1b, 0x76, 0xd7, 0x09, 0xdb, 0x84, 0xd8, 0xcb, 0x43, 0x9c, 0x40, 0xef, 0x8f, 0x38,
	0x0d, 0x89, 0xf0, 0xfa, 0x3a, 0xf3, 0xfa, 0x54, 0x0a, 0x7d, 0x50, 0x0e, 0x5d, 0x5a, 0x5e, 0xc6,
	0xf1, 0x3b, 0xba, 0x20, 0xc2, 0x1b, 0x2a, 0xa4, 0x3d, 0x3b, 0x09, 0x82, 0x42, 0x82, 0x10, 0xec,
	0xab, 0x82, 0xb9, 0x25, 0x81, 0x1d, 0x78, 0x67, 0x70, 0xe0, 0xd0, 0xcc, 0xf5, 0x9d, 0x40, 0x47,
	0x90, 0x20, 0xbb, 0xbb, 0x81, 0xba, 0xbb, 0x5b, 0x12, 0xcc, 0x14, 0x15, 0x3f, 0x82, 0x7d, 0xdd,
	0x1b, 0x25, 0x29, 0xaf, 0x1e, 0x41, 0x82, 0xec, 0xfa, 0x04, 0x09, 0xf0, 0x97, 0x70, 0xe0, 0x48,
	0x19, 0xc5, 0x7e, 0x2e, 0xe6, 0xea, 0x55, 0x00, 0x0c, 0xfb, 0xba, 0xdc, 0x1c, 0xb5, 0xf9, 0x80,
	0x68, 0xcb, 0x1c, 0xe0, 0x2f, 0xe0, 0xc0, 0x91, 0xd9, 0x52, 0x8f, 0x8f, 0xe1, 0x40, 0x57, 0x87,
	0x13, 0x6f, 0x8d, 0xa3, 0xe7, 0x80, 0x5c, 0xb1, 0xff, 0x74, 0x05, 0x4f, 0xa0, 0x7d, 0x4b, 0x82,
	0xb2, 0x7b, 0x99, 0xf2, 0x96, 0x55, 0x7e, 0xfe, 0xf7, 0x10, 0xc6, 0x2f, 0xb3, 0x15, 0xe8, 0xd2,
	0xac, 0x40, 0x17, 0x09, 0x43, 0xbf, 0x9a, 0x5c, 0x38, 0x4b, 0x0c, 0x3a, 0x51, 0x56, 0x36, 0xac,
	0x43, 0xfe, 0xfd, 0x0d, 0x5c, 0xed, 0x30, 0x6e, 0xa0, 0x2b, 0xd8, 0x2d, 0xee, 0x2e, 0xc8, 0x2f,
	0x42, 0xdc, 0x4d, 0xc7, 0x3f, 0xae, 0xe5, 0x59, 0x65, 0xbf, 0x03, 0xaa, 0x6e, 0x17, 0xe8, 0xb4,
	0xb4, 0x4f, 0x95, 0x36, 0x1e, 0xff, 0xb3, 0x8d, 0x7c, 0xab, 0xf8, 0x1b, 0xe8, 0x9b, 0x65, 0x01,
	0x8d, 0x94, 0x74, 0x71, 0xe9, 0xf0, 0xc7, 0x45, 0xa2, 0xc5, 0xfd, 0x04, 0x9f, 0xb8, 0x13, 0x19,
	0x79, 0x4a, 0xae, 0x66, 0xc0, 0xfb, 0xf7, 0x6a, 0x38, 0xae, 0x1a, 0x77, 0xd8, 0x19, 0x35, 0x35,
	0xb3, 0xdb, 0xa8, 0xa9, 0x9b, 0xcc, 0xb8, 0x81, 0xae, 0x61, 0xaf, 0x34, 0x33, 0xd1, 0x71, 0x45,
	0x3e, 0xef, 0xf0, 0xfe, 0x49, 0x3d, 0xd3, 0x75, 0xcb, 0x9d, 0x3d, 0xc6, 0xad, 0x9a, 0x19, 0x6b,
	0xdc, 0xaa, 0x1b, 0xa5, 0xb8, 0x81, 0xe6, 0x85, 0x91, 0xe0, 0x8c, 0x30, 0x84, 0x2b, 0xb0, 0xca,
	0x08, 0xf5, 0x1f, 0xde, 0x29, 0x53, 0xa9, 0xb3, 0x3c, 0x74, 0xbf, 0x0c, 0x74, 0x22, 0x3f, 0xae,
	0xe5, 0xb9, 0x81, 0xbb, 0x43, 0xc6, 0x04, 0x5e, 0x33, 0xa0, 0x4c, 0xe0, 0x75, 0x13, 0x09, 0x37,
	0xd0, 0x4b, 0xf8, 0xb4, 0x30, 0x09, 0x90, 0x96, 0xae, 0x9b, 0x47, 0xbe, 0x5f, 0xc7, 0xb2, 0x9a,
	0xbe, 0x83, 0xa1, 0x6d, 0x88, 0xe8, 0x30, 0x77, 0xde, 0x69, 0x22, 0xfe, 0xa4, 0x4c, 0x76, 0xd1,
	0xb6, 0xeb, 0x19, 0x74, 0xb9, 0x57, 0x1a, 0x74, 0xa5, 0x39, 0x6a, 0xb4, 0x6d, 0x6f, 0x06, 0x5d,
	0x6e, 0x89, 0x06, 0x5d, 0xe9, 0x82, 0xb8, 0x81, 0x7e, 0x00, 0xc8, 0x1b, 0x19, 0x9a, 0x38, 0x51,
	0xba, 0xbe, 0x1f, 0x55, 0xe8, 0x99, 0x82, 0x17, 0xcf, 0xe1, 0x51, 0x14, 0x4f, 0x43, 0xba, 0x60,
	0x64, 0x49, 0xde, 0xd0, 0x68, 0x6a, 0x7f, 0xde, 0xa6, 0xd9, 0xdf, 0x9b, 0x04, 0xbf, 0xa8, 0xed,
	0x68, 0xaf, 0x9a, 0x6f, 0x7a, 0xea, 0xbf, 0xee, 0xab, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x69,
	0x6d, 0xc6, 0xd3, 0xf5, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HarvesterInternalApiClient is the client API for HarvesterInternalApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HarvesterInternalApiClient interface {
	// ITEMS
	FetchItemUpdates(ctx context.Context, in *FetchItemUpdatesRequest, opts ...grpc.CallOption) (*FetchItemUpdatesResponse, error)
	FetchItemTypes(ctx context.Context, in *FetchItemTypesRequest, opts ...grpc.CallOption) (*FetchItemTypesResponse, error)
	UpdateItemInterval(ctx context.Context, in *UpdateItemIntervalRequest, opts ...grpc.CallOption) (*UpdateItemIntervalResponse, error)
	AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemResponse, error)
	// SOURCES
	InsertSource(ctx context.Context, in *InsertSourceRequest, opts ...grpc.CallOption) (*InsertSourceResponse, error)
	UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*UpdateSourceResponse, error)
	UpdateSourceSet(ctx context.Context, in *UpdateSourceSetRequest, opts ...grpc.CallOption) (*UpdateSourceSetResponse, error)
	FetchSources(ctx context.Context, in *FetchSourcesRequest, opts ...grpc.CallOption) (*FetchSourcesResponse, error)
	FetchSourcesPagination(ctx context.Context, in *FetchSourcesPaginationRequest, opts ...grpc.CallOption) (*FetchSourcesPaginationResponse, error)
	FetchSourceSet(ctx context.Context, in *FetchSourceSetRequest, opts ...grpc.CallOption) (*FetchSourceSetResponse, error)
	DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error)
	SearchSources(ctx context.Context, in *SearchSourcesRequest, opts ...grpc.CallOption) (*SearchSourcesResponse, error)
	// TAGS
	FetchTags(ctx context.Context, in *FetchTagsRequest, opts ...grpc.CallOption) (*FetchTagsResponse, error)
	InsertTag(ctx context.Context, in *InsertTagRequest, opts ...grpc.CallOption) (*InsertTagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	SearchTags(ctx context.Context, in *SearchTagsRequest, opts ...grpc.CallOption) (*SearchTagsResponse, error)
}

type harvesterInternalApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHarvesterInternalApiClient(cc grpc.ClientConnInterface) HarvesterInternalApiClient {
	return &harvesterInternalApiClient{cc}
}

func (c *harvesterInternalApiClient) FetchItemUpdates(ctx context.Context, in *FetchItemUpdatesRequest, opts ...grpc.CallOption) (*FetchItemUpdatesResponse, error) {
	out := new(FetchItemUpdatesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchItemUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchItemTypes(ctx context.Context, in *FetchItemTypesRequest, opts ...grpc.CallOption) (*FetchItemTypesResponse, error) {
	out := new(FetchItemTypesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchItemTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) UpdateItemInterval(ctx context.Context, in *UpdateItemIntervalRequest, opts ...grpc.CallOption) (*UpdateItemIntervalResponse, error) {
	out := new(UpdateItemIntervalResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/UpdateItemInterval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) AddItem(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*AddItemResponse, error) {
	out := new(AddItemResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) InsertSource(ctx context.Context, in *InsertSourceRequest, opts ...grpc.CallOption) (*InsertSourceResponse, error) {
	out := new(InsertSourceResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/InsertSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*UpdateSourceResponse, error) {
	out := new(UpdateSourceResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/UpdateSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) UpdateSourceSet(ctx context.Context, in *UpdateSourceSetRequest, opts ...grpc.CallOption) (*UpdateSourceSetResponse, error) {
	out := new(UpdateSourceSetResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/UpdateSourceSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchSources(ctx context.Context, in *FetchSourcesRequest, opts ...grpc.CallOption) (*FetchSourcesResponse, error) {
	out := new(FetchSourcesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchSourcesPagination(ctx context.Context, in *FetchSourcesPaginationRequest, opts ...grpc.CallOption) (*FetchSourcesPaginationResponse, error) {
	out := new(FetchSourcesPaginationResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchSourcesPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchSourceSet(ctx context.Context, in *FetchSourceSetRequest, opts ...grpc.CallOption) (*FetchSourceSetResponse, error) {
	out := new(FetchSourceSetResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchSourceSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error) {
	out := new(DeleteSourceResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/DeleteSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) SearchSources(ctx context.Context, in *SearchSourcesRequest, opts ...grpc.CallOption) (*SearchSourcesResponse, error) {
	out := new(SearchSourcesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/SearchSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchTags(ctx context.Context, in *FetchTagsRequest, opts ...grpc.CallOption) (*FetchTagsResponse, error) {
	out := new(FetchTagsResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) InsertTag(ctx context.Context, in *InsertTagRequest, opts ...grpc.CallOption) (*InsertTagResponse, error) {
	out := new(InsertTagResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/InsertTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/DeleteTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) SearchTags(ctx context.Context, in *SearchTagsRequest, opts ...grpc.CallOption) (*SearchTagsResponse, error) {
	out := new(SearchTagsResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/SearchTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HarvesterInternalApiServer is the server API for HarvesterInternalApi service.
type HarvesterInternalApiServer interface {
	// ITEMS
	FetchItemUpdates(context.Context, *FetchItemUpdatesRequest) (*FetchItemUpdatesResponse, error)
	FetchItemTypes(context.Context, *FetchItemTypesRequest) (*FetchItemTypesResponse, error)
	UpdateItemInterval(context.Context, *UpdateItemIntervalRequest) (*UpdateItemIntervalResponse, error)
	AddItem(context.Context, *AddItemRequest) (*AddItemResponse, error)
	// SOURCES
	InsertSource(context.Context, *InsertSourceRequest) (*InsertSourceResponse, error)
	UpdateSource(context.Context, *UpdateSourceRequest) (*UpdateSourceResponse, error)
	UpdateSourceSet(context.Context, *UpdateSourceSetRequest) (*UpdateSourceSetResponse, error)
	FetchSources(context.Context, *FetchSourcesRequest) (*FetchSourcesResponse, error)
	FetchSourcesPagination(context.Context, *FetchSourcesPaginationRequest) (*FetchSourcesPaginationResponse, error)
	FetchSourceSet(context.Context, *FetchSourceSetRequest) (*FetchSourceSetResponse, error)
	DeleteSource(context.Context, *DeleteSourceRequest) (*DeleteSourceResponse, error)
	SearchSources(context.Context, *SearchSourcesRequest) (*SearchSourcesResponse, error)
	// TAGS
	FetchTags(context.Context, *FetchTagsRequest) (*FetchTagsResponse, error)
	InsertTag(context.Context, *InsertTagRequest) (*InsertTagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	SearchTags(context.Context, *SearchTagsRequest) (*SearchTagsResponse, error)
}

// UnimplementedHarvesterInternalApiServer can be embedded to have forward compatible implementations.
type UnimplementedHarvesterInternalApiServer struct {
}

func (*UnimplementedHarvesterInternalApiServer) FetchItemUpdates(ctx context.Context, req *FetchItemUpdatesRequest) (*FetchItemUpdatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchItemUpdates not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchItemTypes(ctx context.Context, req *FetchItemTypesRequest) (*FetchItemTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchItemTypes not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) UpdateItemInterval(ctx context.Context, req *UpdateItemIntervalRequest) (*UpdateItemIntervalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItemInterval not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) AddItem(ctx context.Context, req *AddItemRequest) (*AddItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) InsertSource(ctx context.Context, req *InsertSourceRequest) (*InsertSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertSource not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) UpdateSource(ctx context.Context, req *UpdateSourceRequest) (*UpdateSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSource not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) UpdateSourceSet(ctx context.Context, req *UpdateSourceSetRequest) (*UpdateSourceSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSourceSet not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchSources(ctx context.Context, req *FetchSourcesRequest) (*FetchSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSources not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchSourcesPagination(ctx context.Context, req *FetchSourcesPaginationRequest) (*FetchSourcesPaginationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSourcesPagination not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchSourceSet(ctx context.Context, req *FetchSourceSetRequest) (*FetchSourceSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSourceSet not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) DeleteSource(ctx context.Context, req *DeleteSourceRequest) (*DeleteSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSource not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) SearchSources(ctx context.Context, req *SearchSourcesRequest) (*SearchSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSources not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchTags(ctx context.Context, req *FetchTagsRequest) (*FetchTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTags not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) InsertTag(ctx context.Context, req *InsertTagRequest) (*InsertTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTag not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) DeleteTag(ctx context.Context, req *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTag not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) SearchTags(ctx context.Context, req *SearchTagsRequest) (*SearchTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTags not implemented")
}

func RegisterHarvesterInternalApiServer(s *grpc.Server, srv HarvesterInternalApiServer) {
	s.RegisterService(&_HarvesterInternalApi_serviceDesc, srv)
}

func _HarvesterInternalApi_FetchItemUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchItemUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchItemUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchItemUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchItemUpdates(ctx, req.(*FetchItemUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchItemTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchItemTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchItemTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchItemTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchItemTypes(ctx, req.(*FetchItemTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_UpdateItemInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemIntervalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).UpdateItemInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/UpdateItemInterval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).UpdateItemInterval(ctx, req.(*UpdateItemIntervalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).AddItem(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_InsertSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).InsertSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/InsertSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).InsertSource(ctx, req.(*InsertSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_UpdateSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).UpdateSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/UpdateSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).UpdateSource(ctx, req.(*UpdateSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_UpdateSourceSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).UpdateSourceSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/UpdateSourceSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).UpdateSourceSet(ctx, req.(*UpdateSourceSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchSources(ctx, req.(*FetchSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchSourcesPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSourcesPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchSourcesPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchSourcesPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchSourcesPagination(ctx, req.(*FetchSourcesPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchSourceSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSourceSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchSourceSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchSourceSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchSourceSet(ctx, req.(*FetchSourceSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/DeleteSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).DeleteSource(ctx, req.(*DeleteSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_SearchSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).SearchSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/SearchSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).SearchSources(ctx, req.(*SearchSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchTags(ctx, req.(*FetchTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_InsertTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).InsertTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/InsertTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).InsertTag(ctx, req.(*InsertTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/DeleteTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_SearchTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).SearchTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/SearchTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).SearchTags(ctx, req.(*SearchTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HarvesterInternalApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HarvesterInternalApi",
	HandlerType: (*HarvesterInternalApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchItemUpdates",
			Handler:    _HarvesterInternalApi_FetchItemUpdates_Handler,
		},
		{
			MethodName: "FetchItemTypes",
			Handler:    _HarvesterInternalApi_FetchItemTypes_Handler,
		},
		{
			MethodName: "UpdateItemInterval",
			Handler:    _HarvesterInternalApi_UpdateItemInterval_Handler,
		},
		{
			MethodName: "AddItem",
			Handler:    _HarvesterInternalApi_AddItem_Handler,
		},
		{
			MethodName: "InsertSource",
			Handler:    _HarvesterInternalApi_InsertSource_Handler,
		},
		{
			MethodName: "UpdateSource",
			Handler:    _HarvesterInternalApi_UpdateSource_Handler,
		},
		{
			MethodName: "UpdateSourceSet",
			Handler:    _HarvesterInternalApi_UpdateSourceSet_Handler,
		},
		{
			MethodName: "FetchSources",
			Handler:    _HarvesterInternalApi_FetchSources_Handler,
		},
		{
			MethodName: "FetchSourcesPagination",
			Handler:    _HarvesterInternalApi_FetchSourcesPagination_Handler,
		},
		{
			MethodName: "FetchSourceSet",
			Handler:    _HarvesterInternalApi_FetchSourceSet_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _HarvesterInternalApi_DeleteSource_Handler,
		},
		{
			MethodName: "SearchSources",
			Handler:    _HarvesterInternalApi_SearchSources_Handler,
		},
		{
			MethodName: "FetchTags",
			Handler:    _HarvesterInternalApi_FetchTags_Handler,
		},
		{
			MethodName: "InsertTag",
			Handler:    _HarvesterInternalApi_InsertTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _HarvesterInternalApi_DeleteTag_Handler,
		},
		{
			MethodName: "SearchTags",
			Handler:    _HarvesterInternalApi_SearchTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "harvesterinternalapi.proto",
}
