// Code generated by protoc-gen-go. DO NOT EDIT.
// source: harvesterinternalapi.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchItemUpdatesRequest struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchItemUpdatesRequest) Reset()         { *m = FetchItemUpdatesRequest{} }
func (m *FetchItemUpdatesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchItemUpdatesRequest) ProtoMessage()    {}
func (*FetchItemUpdatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{0}
}

func (m *FetchItemUpdatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemUpdatesRequest.Unmarshal(m, b)
}
func (m *FetchItemUpdatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemUpdatesRequest.Marshal(b, m, deterministic)
}
func (m *FetchItemUpdatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemUpdatesRequest.Merge(m, src)
}
func (m *FetchItemUpdatesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchItemUpdatesRequest.Size(m)
}
func (m *FetchItemUpdatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemUpdatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemUpdatesRequest proto.InternalMessageInfo

func (m *FetchItemUpdatesRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type FetchItemUpdatesResponse struct {
	Items                []*UpdateItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FetchItemUpdatesResponse) Reset()         { *m = FetchItemUpdatesResponse{} }
func (m *FetchItemUpdatesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchItemUpdatesResponse) ProtoMessage()    {}
func (*FetchItemUpdatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{1}
}

func (m *FetchItemUpdatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemUpdatesResponse.Unmarshal(m, b)
}
func (m *FetchItemUpdatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemUpdatesResponse.Marshal(b, m, deterministic)
}
func (m *FetchItemUpdatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemUpdatesResponse.Merge(m, src)
}
func (m *FetchItemUpdatesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchItemUpdatesResponse.Size(m)
}
func (m *FetchItemUpdatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemUpdatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemUpdatesResponse proto.InternalMessageInfo

func (m *FetchItemUpdatesResponse) GetItems() []*UpdateItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type FetchItemTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchItemTypesRequest) Reset()         { *m = FetchItemTypesRequest{} }
func (m *FetchItemTypesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchItemTypesRequest) ProtoMessage()    {}
func (*FetchItemTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{2}
}

func (m *FetchItemTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemTypesRequest.Unmarshal(m, b)
}
func (m *FetchItemTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemTypesRequest.Marshal(b, m, deterministic)
}
func (m *FetchItemTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemTypesRequest.Merge(m, src)
}
func (m *FetchItemTypesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchItemTypesRequest.Size(m)
}
func (m *FetchItemTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemTypesRequest proto.InternalMessageInfo

type FetchItemTypesResponse struct {
	Types                []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchItemTypesResponse) Reset()         { *m = FetchItemTypesResponse{} }
func (m *FetchItemTypesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchItemTypesResponse) ProtoMessage()    {}
func (*FetchItemTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{3}
}

func (m *FetchItemTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchItemTypesResponse.Unmarshal(m, b)
}
func (m *FetchItemTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchItemTypesResponse.Marshal(b, m, deterministic)
}
func (m *FetchItemTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchItemTypesResponse.Merge(m, src)
}
func (m *FetchItemTypesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchItemTypesResponse.Size(m)
}
func (m *FetchItemTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchItemTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchItemTypesResponse proto.InternalMessageInfo

func (m *FetchItemTypesResponse) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

type UpdateItemIntervalRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Interval             int32    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemIntervalRequest) Reset()         { *m = UpdateItemIntervalRequest{} }
func (m *UpdateItemIntervalRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateItemIntervalRequest) ProtoMessage()    {}
func (*UpdateItemIntervalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{4}
}

func (m *UpdateItemIntervalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemIntervalRequest.Unmarshal(m, b)
}
func (m *UpdateItemIntervalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemIntervalRequest.Marshal(b, m, deterministic)
}
func (m *UpdateItemIntervalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemIntervalRequest.Merge(m, src)
}
func (m *UpdateItemIntervalRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateItemIntervalRequest.Size(m)
}
func (m *UpdateItemIntervalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemIntervalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemIntervalRequest proto.InternalMessageInfo

func (m *UpdateItemIntervalRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateItemIntervalRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *UpdateItemIntervalRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *UpdateItemIntervalRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type UpdateItemIntervalResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemIntervalResponse) Reset()         { *m = UpdateItemIntervalResponse{} }
func (m *UpdateItemIntervalResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateItemIntervalResponse) ProtoMessage()    {}
func (*UpdateItemIntervalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{5}
}

func (m *UpdateItemIntervalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemIntervalResponse.Unmarshal(m, b)
}
func (m *UpdateItemIntervalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemIntervalResponse.Marshal(b, m, deterministic)
}
func (m *UpdateItemIntervalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemIntervalResponse.Merge(m, src)
}
func (m *UpdateItemIntervalResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateItemIntervalResponse.Size(m)
}
func (m *UpdateItemIntervalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemIntervalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemIntervalResponse proto.InternalMessageInfo

func (m *UpdateItemIntervalResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateItemIntervalResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Interval             int32    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItem) Reset()         { *m = UpdateItem{} }
func (m *UpdateItem) String() string { return proto.CompactTextString(m) }
func (*UpdateItem) ProtoMessage()    {}
func (*UpdateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{6}
}

func (m *UpdateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItem.Unmarshal(m, b)
}
func (m *UpdateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItem.Marshal(b, m, deterministic)
}
func (m *UpdateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItem.Merge(m, src)
}
func (m *UpdateItem) XXX_Size() int {
	return xxx_messageInfo_UpdateItem.Size(m)
}
func (m *UpdateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItem.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItem proto.InternalMessageInfo

func (m *UpdateItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateItem) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *UpdateItem) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *UpdateItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type InsertSourceRequest struct {
	Source               *Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertSourceRequest) Reset()         { *m = InsertSourceRequest{} }
func (m *InsertSourceRequest) String() string { return proto.CompactTextString(m) }
func (*InsertSourceRequest) ProtoMessage()    {}
func (*InsertSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{7}
}

func (m *InsertSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertSourceRequest.Unmarshal(m, b)
}
func (m *InsertSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertSourceRequest.Marshal(b, m, deterministic)
}
func (m *InsertSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertSourceRequest.Merge(m, src)
}
func (m *InsertSourceRequest) XXX_Size() int {
	return xxx_messageInfo_InsertSourceRequest.Size(m)
}
func (m *InsertSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertSourceRequest proto.InternalMessageInfo

func (m *InsertSourceRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type InsertSourceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertSourceResponse) Reset()         { *m = InsertSourceResponse{} }
func (m *InsertSourceResponse) String() string { return proto.CompactTextString(m) }
func (*InsertSourceResponse) ProtoMessage()    {}
func (*InsertSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{8}
}

func (m *InsertSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertSourceResponse.Unmarshal(m, b)
}
func (m *InsertSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertSourceResponse.Marshal(b, m, deterministic)
}
func (m *InsertSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertSourceResponse.Merge(m, src)
}
func (m *InsertSourceResponse) XXX_Size() int {
	return xxx_messageInfo_InsertSourceResponse.Size(m)
}
func (m *InsertSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertSourceResponse proto.InternalMessageInfo

func (m *InsertSourceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateSourceRequest struct {
	Source               *Source  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceRequest) Reset()         { *m = UpdateSourceRequest{} }
func (m *UpdateSourceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceRequest) ProtoMessage()    {}
func (*UpdateSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{9}
}

func (m *UpdateSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceRequest.Unmarshal(m, b)
}
func (m *UpdateSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceRequest.Merge(m, src)
}
func (m *UpdateSourceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceRequest.Size(m)
}
func (m *UpdateSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceRequest proto.InternalMessageInfo

func (m *UpdateSourceRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type UpdateSourceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceResponse) Reset()         { *m = UpdateSourceResponse{} }
func (m *UpdateSourceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceResponse) ProtoMessage()    {}
func (*UpdateSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{10}
}

func (m *UpdateSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceResponse.Unmarshal(m, b)
}
func (m *UpdateSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceResponse.Merge(m, src)
}
func (m *UpdateSourceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceResponse.Size(m)
}
func (m *UpdateSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceResponse proto.InternalMessageInfo

func (m *UpdateSourceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateSourceSetRequest struct {
	SetKey               string   `protobuf:"bytes,2,opt,name=set_key,json=setKey,proto3" json:"set_key,omitempty"`
	ItemKeys             []string `protobuf:"bytes,3,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceSetRequest) Reset()         { *m = UpdateSourceSetRequest{} }
func (m *UpdateSourceSetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceSetRequest) ProtoMessage()    {}
func (*UpdateSourceSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{11}
}

func (m *UpdateSourceSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceSetRequest.Unmarshal(m, b)
}
func (m *UpdateSourceSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceSetRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSourceSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceSetRequest.Merge(m, src)
}
func (m *UpdateSourceSetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceSetRequest.Size(m)
}
func (m *UpdateSourceSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceSetRequest proto.InternalMessageInfo

func (m *UpdateSourceSetRequest) GetSetKey() string {
	if m != nil {
		return m.SetKey
	}
	return ""
}

func (m *UpdateSourceSetRequest) GetItemKeys() []string {
	if m != nil {
		return m.ItemKeys
	}
	return nil
}

type UpdateSourceSetResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSourceSetResponse) Reset()         { *m = UpdateSourceSetResponse{} }
func (m *UpdateSourceSetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSourceSetResponse) ProtoMessage()    {}
func (*UpdateSourceSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{12}
}

func (m *UpdateSourceSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSourceSetResponse.Unmarshal(m, b)
}
func (m *UpdateSourceSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSourceSetResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSourceSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSourceSetResponse.Merge(m, src)
}
func (m *UpdateSourceSetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSourceSetResponse.Size(m)
}
func (m *UpdateSourceSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSourceSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSourceSetResponse proto.InternalMessageInfo

func (m *UpdateSourceSetResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FetchSourcesRequest struct {
	Priority             int32    `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourcesRequest) Reset()         { *m = FetchSourcesRequest{} }
func (m *FetchSourcesRequest) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesRequest) ProtoMessage()    {}
func (*FetchSourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{13}
}

func (m *FetchSourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesRequest.Unmarshal(m, b)
}
func (m *FetchSourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesRequest.Marshal(b, m, deterministic)
}
func (m *FetchSourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesRequest.Merge(m, src)
}
func (m *FetchSourcesRequest) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesRequest.Size(m)
}
func (m *FetchSourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesRequest proto.InternalMessageInfo

func (m *FetchSourcesRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type FetchSourcesResponse struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FetchSourcesResponse) Reset()         { *m = FetchSourcesResponse{} }
func (m *FetchSourcesResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesResponse) ProtoMessage()    {}
func (*FetchSourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{14}
}

func (m *FetchSourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesResponse.Unmarshal(m, b)
}
func (m *FetchSourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesResponse.Marshal(b, m, deterministic)
}
func (m *FetchSourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesResponse.Merge(m, src)
}
func (m *FetchSourcesResponse) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesResponse.Size(m)
}
func (m *FetchSourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesResponse proto.InternalMessageInfo

func (m *FetchSourcesResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

type FetchSourcesPaginationRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Skip                 int32    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Cursor               string   `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourcesPaginationRequest) Reset()         { *m = FetchSourcesPaginationRequest{} }
func (m *FetchSourcesPaginationRequest) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesPaginationRequest) ProtoMessage()    {}
func (*FetchSourcesPaginationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{15}
}

func (m *FetchSourcesPaginationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesPaginationRequest.Unmarshal(m, b)
}
func (m *FetchSourcesPaginationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesPaginationRequest.Marshal(b, m, deterministic)
}
func (m *FetchSourcesPaginationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesPaginationRequest.Merge(m, src)
}
func (m *FetchSourcesPaginationRequest) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesPaginationRequest.Size(m)
}
func (m *FetchSourcesPaginationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesPaginationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesPaginationRequest proto.InternalMessageInfo

func (m *FetchSourcesPaginationRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FetchSourcesPaginationRequest) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *FetchSourcesPaginationRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type FetchSourcesPaginationResponse struct {
	Sources              []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Cursor               string    `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FetchSourcesPaginationResponse) Reset()         { *m = FetchSourcesPaginationResponse{} }
func (m *FetchSourcesPaginationResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSourcesPaginationResponse) ProtoMessage()    {}
func (*FetchSourcesPaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{16}
}

func (m *FetchSourcesPaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourcesPaginationResponse.Unmarshal(m, b)
}
func (m *FetchSourcesPaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourcesPaginationResponse.Marshal(b, m, deterministic)
}
func (m *FetchSourcesPaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourcesPaginationResponse.Merge(m, src)
}
func (m *FetchSourcesPaginationResponse) XXX_Size() int {
	return xxx_messageInfo_FetchSourcesPaginationResponse.Size(m)
}
func (m *FetchSourcesPaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourcesPaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourcesPaginationResponse proto.InternalMessageInfo

func (m *FetchSourcesPaginationResponse) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *FetchSourcesPaginationResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type FetchSourceSetRequest struct {
	SetKey               string   `protobuf:"bytes,1,opt,name=set_key,json=setKey,proto3" json:"set_key,omitempty"`
	ItemKeys             []string `protobuf:"bytes,2,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourceSetRequest) Reset()         { *m = FetchSourceSetRequest{} }
func (m *FetchSourceSetRequest) String() string { return proto.CompactTextString(m) }
func (*FetchSourceSetRequest) ProtoMessage()    {}
func (*FetchSourceSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{17}
}

func (m *FetchSourceSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourceSetRequest.Unmarshal(m, b)
}
func (m *FetchSourceSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourceSetRequest.Marshal(b, m, deterministic)
}
func (m *FetchSourceSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourceSetRequest.Merge(m, src)
}
func (m *FetchSourceSetRequest) XXX_Size() int {
	return xxx_messageInfo_FetchSourceSetRequest.Size(m)
}
func (m *FetchSourceSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourceSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourceSetRequest proto.InternalMessageInfo

func (m *FetchSourceSetRequest) GetSetKey() string {
	if m != nil {
		return m.SetKey
	}
	return ""
}

func (m *FetchSourceSetRequest) GetItemKeys() []string {
	if m != nil {
		return m.ItemKeys
	}
	return nil
}

type FetchSourceSetResponse struct {
	ItemKeys             []string `protobuf:"bytes,1,rep,name=item_keys,json=itemKeys,proto3" json:"item_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchSourceSetResponse) Reset()         { *m = FetchSourceSetResponse{} }
func (m *FetchSourceSetResponse) String() string { return proto.CompactTextString(m) }
func (*FetchSourceSetResponse) ProtoMessage()    {}
func (*FetchSourceSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{18}
}

func (m *FetchSourceSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchSourceSetResponse.Unmarshal(m, b)
}
func (m *FetchSourceSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchSourceSetResponse.Marshal(b, m, deterministic)
}
func (m *FetchSourceSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchSourceSetResponse.Merge(m, src)
}
func (m *FetchSourceSetResponse) XXX_Size() int {
	return xxx_messageInfo_FetchSourceSetResponse.Size(m)
}
func (m *FetchSourceSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchSourceSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchSourceSetResponse proto.InternalMessageInfo

func (m *FetchSourceSetResponse) GetItemKeys() []string {
	if m != nil {
		return m.ItemKeys
	}
	return nil
}

type DeleteSourceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSourceRequest) Reset()         { *m = DeleteSourceRequest{} }
func (m *DeleteSourceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSourceRequest) ProtoMessage()    {}
func (*DeleteSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{19}
}

func (m *DeleteSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSourceRequest.Unmarshal(m, b)
}
func (m *DeleteSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSourceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSourceRequest.Merge(m, src)
}
func (m *DeleteSourceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSourceRequest.Size(m)
}
func (m *DeleteSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSourceRequest proto.InternalMessageInfo

func (m *DeleteSourceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteSourceResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSourceResponse) Reset()         { *m = DeleteSourceResponse{} }
func (m *DeleteSourceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSourceResponse) ProtoMessage()    {}
func (*DeleteSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{20}
}

func (m *DeleteSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSourceResponse.Unmarshal(m, b)
}
func (m *DeleteSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSourceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSourceResponse.Merge(m, src)
}
func (m *DeleteSourceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSourceResponse.Size(m)
}
func (m *DeleteSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSourceResponse proto.InternalMessageInfo

func (m *DeleteSourceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Source struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority             int32    `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Format               string   `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	Categories           []string `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
	Lookedat             string   `protobuf:"bytes,9,opt,name=lookedat,proto3" json:"lookedat,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_956f1945bd8023db, []int{21}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Source) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Source) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Source) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Source) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Source) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Source) GetLookedat() string {
	if m != nil {
		return m.Lookedat
	}
	return ""
}

func (m *Source) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*FetchItemUpdatesRequest)(nil), "api.FetchItemUpdatesRequest")
	proto.RegisterType((*FetchItemUpdatesResponse)(nil), "api.FetchItemUpdatesResponse")
	proto.RegisterType((*FetchItemTypesRequest)(nil), "api.FetchItemTypesRequest")
	proto.RegisterType((*FetchItemTypesResponse)(nil), "api.FetchItemTypesResponse")
	proto.RegisterType((*UpdateItemIntervalRequest)(nil), "api.UpdateItemIntervalRequest")
	proto.RegisterType((*UpdateItemIntervalResponse)(nil), "api.UpdateItemIntervalResponse")
	proto.RegisterType((*UpdateItem)(nil), "api.UpdateItem")
	proto.RegisterType((*InsertSourceRequest)(nil), "api.InsertSourceRequest")
	proto.RegisterType((*InsertSourceResponse)(nil), "api.InsertSourceResponse")
	proto.RegisterType((*UpdateSourceRequest)(nil), "api.UpdateSourceRequest")
	proto.RegisterType((*UpdateSourceResponse)(nil), "api.UpdateSourceResponse")
	proto.RegisterType((*UpdateSourceSetRequest)(nil), "api.UpdateSourceSetRequest")
	proto.RegisterType((*UpdateSourceSetResponse)(nil), "api.UpdateSourceSetResponse")
	proto.RegisterType((*FetchSourcesRequest)(nil), "api.FetchSourcesRequest")
	proto.RegisterType((*FetchSourcesResponse)(nil), "api.FetchSourcesResponse")
	proto.RegisterType((*FetchSourcesPaginationRequest)(nil), "api.FetchSourcesPaginationRequest")
	proto.RegisterType((*FetchSourcesPaginationResponse)(nil), "api.FetchSourcesPaginationResponse")
	proto.RegisterType((*FetchSourceSetRequest)(nil), "api.FetchSourceSetRequest")
	proto.RegisterType((*FetchSourceSetResponse)(nil), "api.FetchSourceSetResponse")
	proto.RegisterType((*DeleteSourceRequest)(nil), "api.DeleteSourceRequest")
	proto.RegisterType((*DeleteSourceResponse)(nil), "api.DeleteSourceResponse")
	proto.RegisterType((*Source)(nil), "api.Source")
}

func init() { proto.RegisterFile("harvesterinternalapi.proto", fileDescriptor_956f1945bd8023db) }

var fileDescriptor_956f1945bd8023db = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x4f, 0x1b, 0x3b,
	0x10, 0xce, 0xe6, 0xb2, 0x49, 0x86, 0x23, 0x40, 0x26, 0x27, 0x2c, 0x1b, 0xe0, 0x20, 0x73, 0x90,
	0x78, 0x8a, 0x04, 0x47, 0xe7, 0xa5, 0x52, 0x2b, 0x81, 0xda, 0xaa, 0x11, 0x2a, 0xa2, 0xa1, 0x55,
	0x1f, 0x91, 0x49, 0x5c, 0x70, 0xc9, 0x5e, 0x6a, 0x3b, 0x48, 0xf9, 0x51, 0xfd, 0x67, 0xfd, 0x11,
	0x95, 0xbd, 0xde, 0x8d, 0xf7, 0x12, 0x50, 0x2b, 0xf5, 0x6d, 0xc7, 0x33, 0xdf, 0x5c, 0xec, 0x99,
	0x6f, 0x16, 0xfc, 0x7b, 0xc2, 0x1f, 0xa9, 0x90, 0x94, 0xb3, 0x50, 0x52, 0x1e, 0x92, 0x19, 0x89,
	0xd9, 0x30, 0xe6, 0x91, 0x8c, 0x50, 0x83, 0xc4, 0x0c, 0x9f, 0xc0, 0xf6, 0x5b, 0x2a, 0x27, 0xf7,
	0x23, 0x49, 0x83, 0x4f, 0xf1, 0x94, 0x48, 0x2a, 0xc6, 0xf4, 0xdb, 0x9c, 0x0a, 0x89, 0xfa, 0xe0,
	0x92, 0x20, 0x9a, 0x87, 0xd2, 0x73, 0x0e, 0x9c, 0xe3, 0xd6, 0xd8, 0x48, 0xf8, 0x0c, 0xbc, 0x32,
	0x44, 0xc4, 0x51, 0x28, 0x28, 0x3a, 0x82, 0x16, 0x93, 0x34, 0x10, 0x9e, 0x73, 0xd0, 0x38, 0x5e,
	0x3b, 0xdd, 0x18, 0xaa, 0x70, 0x89, 0x91, 0x32, 0x1f, 0x27, 0x5a, 0xbc, 0x0d, 0x7f, 0x67, 0x2e,
	0x3e, 0x2e, 0xe2, 0x2c, 0x26, 0x1e, 0x42, 0xbf, 0xa8, 0x30, 0x9e, 0x7b, 0xd0, 0x92, 0xea, 0x40,
	0x7b, 0xee, 0x8e, 0x13, 0x01, 0x2f, 0x60, 0x67, 0xe9, 0x7d, 0xa4, 0x4a, 0x7c, 0x24, 0xb3, 0xb4,
	0x80, 0x75, 0xa8, 0xb3, 0xa9, 0x4e, 0xbe, 0x3b, 0xae, 0xb3, 0x29, 0xf2, 0xa1, 0xc3, 0x8c, 0x89,
	0x57, 0xd7, 0x25, 0x65, 0x32, 0xda, 0x85, 0xae, 0x64, 0x01, 0x15, 0x92, 0x04, 0xb1, 0xd7, 0xd0,
	0x90, 0xe5, 0x01, 0x42, 0xd0, 0x54, 0xf1, 0xbc, 0xa6, 0x56, 0xe8, 0x6f, 0x7c, 0x09, 0x7e, 0x55,
	0x68, 0x93, 0x6e, 0x1f, 0x5c, 0x21, 0x89, 0x9c, 0x8b, 0xf4, 0xf2, 0x12, 0x09, 0x79, 0xd0, 0x0e,
	0xa8, 0x10, 0xe4, 0x8e, 0xea, 0x14, 0xba, 0xe3, 0x54, 0xc4, 0x5f, 0x01, 0x96, 0xfe, 0xfe, 0x70,
	0xee, 0x2f, 0x60, 0x6b, 0x14, 0x0a, 0xca, 0xe5, 0x75, 0x34, 0xe7, 0x13, 0x9a, 0x5e, 0xd8, 0x21,
	0xb8, 0x42, 0x1f, 0xe8, 0xc0, 0x6b, 0xa7, 0x6b, 0xfa, 0xf9, 0x8c, 0x8d, 0x51, 0xe1, 0x21, 0xf4,
	0xf2, 0xd8, 0xa7, 0x2b, 0x56, 0xb1, 0x92, 0xba, 0x7e, 0x2f, 0x56, 0x1e, 0xfb, 0x4c, 0xac, 0x4b,
	0xe8, 0xdb, 0xf6, 0xd7, 0x54, 0xa6, 0xe1, 0xb6, 0xa1, 0x2d, 0xa8, 0xbc, 0x79, 0xa0, 0x0b, 0x73,
	0xef, 0xae, 0xa0, 0xf2, 0x82, 0x2e, 0xd0, 0x00, 0xba, 0xaa, 0x27, 0x95, 0x46, 0x78, 0x0d, 0xdd,
	0x5b, 0x1d, 0x75, 0x70, 0x41, 0x17, 0x42, 0x4d, 0x47, 0xc9, 0xdf, 0x33, 0x29, 0x9c, 0xc0, 0x96,
	0xee, 0xe0, 0x04, 0x91, 0x0d, 0x93, 0x0f, 0x9d, 0x98, 0xb3, 0x88, 0x33, 0xb9, 0x30, 0x80, 0x4c,
	0xc6, 0x2f, 0xa1, 0x97, 0x87, 0x64, 0xc3, 0xd4, 0x4e, 0xee, 0x21, 0x1d, 0xa7, 0xdc, 0x1d, 0xa5,
	0x3a, 0x7c, 0x03, 0x7b, 0x36, 0xfc, 0x8a, 0xdc, 0xb1, 0x90, 0x48, 0x16, 0x85, 0x69, 0xec, 0xb4,
	0x03, 0x9c, 0x65, 0x07, 0xa8, 0x33, 0xf1, 0xc0, 0x62, 0xd3, 0x4b, 0xfa, 0x5b, 0x95, 0x34, 0x99,
	0x73, 0x11, 0x71, 0xd3, 0x44, 0x46, 0xc2, 0x37, 0xb0, 0xbf, 0x2a, 0xc0, 0x2f, 0x65, 0x6a, 0x05,
	0xa8, 0xe7, 0x02, 0xbc, 0x37, 0x74, 0xf0, 0xd4, 0xab, 0x39, 0xab, 0x5f, 0xad, 0x5e, 0x78, 0xb5,
	0xff, 0x0d, 0x89, 0x94, 0x1f, 0x2d, 0x07, 0x73, 0x0a, 0xb0, 0x23, 0xd8, 0x7a, 0x4d, 0x67, 0xb4,
	0xd8, 0xa8, 0x85, 0x49, 0x54, 0x3d, 0x99, 0x37, 0x7b, 0xa6, 0x21, 0x7e, 0x38, 0xe0, 0x26, 0xa6,
	0x68, 0x13, 0x1a, 0xcb, 0x52, 0xd4, 0xa7, 0x71, 0x5e, 0xcf, 0xc6, 0x1c, 0x41, 0x33, 0x24, 0x01,
	0x35, 0x0f, 0xa0, 0xbf, 0x73, 0xad, 0xd3, 0xcc, 0xb7, 0x4e, 0xf6, 0xb4, 0x2d, 0xeb, 0x69, 0x37,
	0xa1, 0x31, 0xe7, 0x33, 0xcf, 0x4d, 0xa2, 0xcc, 0xf9, 0x4c, 0xa5, 0xf6, 0x25, 0xe2, 0x01, 0x91,
	0x5e, 0x3b, 0xb9, 0xc5, 0x44, 0x42, 0xfb, 0x00, 0x13, 0x22, 0xe9, 0x5d, 0xc4, 0x19, 0x15, 0x5e,
	0x47, 0xdf, 0x87, 0x75, 0xa2, 0x22, 0xcf, 0xa2, 0xe8, 0x81, 0x4e, 0x89, 0xf4, 0xba, 0x1a, 0x99,
	0xc9, 0x56, 0xb9, 0x60, 0x97, 0x7b, 0xfa, 0xdd, 0x85, 0xde, 0xbb, 0x74, 0xe9, 0x8c, 0xcc, 0xd2,
	0x39, 0x8b, 0x19, 0xfa, 0x00, 0x9b, 0xc5, 0xb5, 0x81, 0x76, 0x75, 0x9b, 0xac, 0x58, 0x40, 0xfe,
	0xde, 0x0a, 0x6d, 0x72, 0xe1, 0xb8, 0x86, 0x2e, 0x60, 0x3d, 0xbf, 0x2d, 0x90, 0x9f, 0x87, 0xd8,
	0xbb, 0xc5, 0x1f, 0x54, 0xea, 0x32, 0x67, 0x9f, 0x01, 0x95, 0xf9, 0x1c, 0xed, 0x17, 0x36, 0x58,
	0x61, 0xc7, 0xf8, 0xff, 0xac, 0xd4, 0x67, 0x8e, 0xdf, 0xc0, 0x5f, 0x36, 0x61, 0x22, 0x4f, 0x43,
	0x2a, 0xf8, 0xd7, 0xdf, 0xa9, 0xd0, 0xd8, 0x6e, 0x6c, 0x2e, 0x32, 0x6e, 0x2a, 0xa8, 0xd5, 0xb8,
	0xa9, 0x22, 0x4e, 0x5c, 0x43, 0x97, 0xb0, 0x51, 0xa0, 0x34, 0x34, 0x28, 0xd9, 0x2f, 0x47, 0xd0,
	0xdf, 0xad, 0x56, 0xda, 0x69, 0xd9, 0xe4, 0x60, 0xd2, 0xaa, 0xa0, 0x40, 0x93, 0x56, 0x15, 0xd3,
	0xe1, 0x1a, 0x9a, 0xe4, 0x66, 0xd6, 0xe2, 0x18, 0x84, 0x4b, 0xb0, 0x12, 0xc3, 0xf9, 0x87, 0x4f,
	0xda, 0x94, 0xfa, 0x65, 0x59, 0xba, 0x5f, 0x04, 0x5a, 0x95, 0x0f, 0x2a, 0x75, 0x76, 0xe1, 0x36,
	0x0f, 0x98, 0xc2, 0x2b, 0x18, 0xc4, 0x14, 0x5e, 0x45, 0x1a, 0xb8, 0x76, 0xfe, 0x0a, 0xfe, 0x0d,
	0xa3, 0x61, 0x40, 0xa7, 0x8c, 0xcc, 0xc8, 0x2d, 0x0d, 0x87, 0xd9, 0x1f, 0xdb, 0x30, 0xfd, 0x65,
	0x53, 0xf0, 0xf3, 0xca, 0xa1, 0xba, 0x72, 0x6e, 0x5d, 0xfd, 0x33, 0xf7, 0xdf, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0x6f, 0xe5, 0xec, 0xea, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HarvesterInternalApiClient is the client API for HarvesterInternalApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HarvesterInternalApiClient interface {
	// ITEMS
	FetchItemUpdates(ctx context.Context, in *FetchItemUpdatesRequest, opts ...grpc.CallOption) (*FetchItemUpdatesResponse, error)
	FetchItemTypes(ctx context.Context, in *FetchItemTypesRequest, opts ...grpc.CallOption) (*FetchItemTypesResponse, error)
	UpdateItemInterval(ctx context.Context, in *UpdateItemIntervalRequest, opts ...grpc.CallOption) (*UpdateItemIntervalResponse, error)
	// SOURCES
	InsertSource(ctx context.Context, in *InsertSourceRequest, opts ...grpc.CallOption) (*InsertSourceResponse, error)
	UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*UpdateSourceResponse, error)
	UpdateSourceSet(ctx context.Context, in *UpdateSourceSetRequest, opts ...grpc.CallOption) (*UpdateSourceSetResponse, error)
	FetchSources(ctx context.Context, in *FetchSourcesRequest, opts ...grpc.CallOption) (*FetchSourcesResponse, error)
	FetchSourcesPagination(ctx context.Context, in *FetchSourcesPaginationRequest, opts ...grpc.CallOption) (*FetchSourcesPaginationResponse, error)
	FetchSourceSet(ctx context.Context, in *FetchSourceSetRequest, opts ...grpc.CallOption) (*FetchSourceSetResponse, error)
	DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error)
}

type harvesterInternalApiClient struct {
	cc *grpc.ClientConn
}

func NewHarvesterInternalApiClient(cc *grpc.ClientConn) HarvesterInternalApiClient {
	return &harvesterInternalApiClient{cc}
}

func (c *harvesterInternalApiClient) FetchItemUpdates(ctx context.Context, in *FetchItemUpdatesRequest, opts ...grpc.CallOption) (*FetchItemUpdatesResponse, error) {
	out := new(FetchItemUpdatesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchItemUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchItemTypes(ctx context.Context, in *FetchItemTypesRequest, opts ...grpc.CallOption) (*FetchItemTypesResponse, error) {
	out := new(FetchItemTypesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchItemTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) UpdateItemInterval(ctx context.Context, in *UpdateItemIntervalRequest, opts ...grpc.CallOption) (*UpdateItemIntervalResponse, error) {
	out := new(UpdateItemIntervalResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/UpdateItemInterval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) InsertSource(ctx context.Context, in *InsertSourceRequest, opts ...grpc.CallOption) (*InsertSourceResponse, error) {
	out := new(InsertSourceResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/InsertSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*UpdateSourceResponse, error) {
	out := new(UpdateSourceResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/UpdateSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) UpdateSourceSet(ctx context.Context, in *UpdateSourceSetRequest, opts ...grpc.CallOption) (*UpdateSourceSetResponse, error) {
	out := new(UpdateSourceSetResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/UpdateSourceSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchSources(ctx context.Context, in *FetchSourcesRequest, opts ...grpc.CallOption) (*FetchSourcesResponse, error) {
	out := new(FetchSourcesResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchSourcesPagination(ctx context.Context, in *FetchSourcesPaginationRequest, opts ...grpc.CallOption) (*FetchSourcesPaginationResponse, error) {
	out := new(FetchSourcesPaginationResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchSourcesPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) FetchSourceSet(ctx context.Context, in *FetchSourceSetRequest, opts ...grpc.CallOption) (*FetchSourceSetResponse, error) {
	out := new(FetchSourceSetResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/FetchSourceSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harvesterInternalApiClient) DeleteSource(ctx context.Context, in *DeleteSourceRequest, opts ...grpc.CallOption) (*DeleteSourceResponse, error) {
	out := new(DeleteSourceResponse)
	err := c.cc.Invoke(ctx, "/api.HarvesterInternalApi/DeleteSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HarvesterInternalApiServer is the server API for HarvesterInternalApi service.
type HarvesterInternalApiServer interface {
	// ITEMS
	FetchItemUpdates(context.Context, *FetchItemUpdatesRequest) (*FetchItemUpdatesResponse, error)
	FetchItemTypes(context.Context, *FetchItemTypesRequest) (*FetchItemTypesResponse, error)
	UpdateItemInterval(context.Context, *UpdateItemIntervalRequest) (*UpdateItemIntervalResponse, error)
	// SOURCES
	InsertSource(context.Context, *InsertSourceRequest) (*InsertSourceResponse, error)
	UpdateSource(context.Context, *UpdateSourceRequest) (*UpdateSourceResponse, error)
	UpdateSourceSet(context.Context, *UpdateSourceSetRequest) (*UpdateSourceSetResponse, error)
	FetchSources(context.Context, *FetchSourcesRequest) (*FetchSourcesResponse, error)
	FetchSourcesPagination(context.Context, *FetchSourcesPaginationRequest) (*FetchSourcesPaginationResponse, error)
	FetchSourceSet(context.Context, *FetchSourceSetRequest) (*FetchSourceSetResponse, error)
	DeleteSource(context.Context, *DeleteSourceRequest) (*DeleteSourceResponse, error)
}

// UnimplementedHarvesterInternalApiServer can be embedded to have forward compatible implementations.
type UnimplementedHarvesterInternalApiServer struct {
}

func (*UnimplementedHarvesterInternalApiServer) FetchItemUpdates(ctx context.Context, req *FetchItemUpdatesRequest) (*FetchItemUpdatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchItemUpdates not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchItemTypes(ctx context.Context, req *FetchItemTypesRequest) (*FetchItemTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchItemTypes not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) UpdateItemInterval(ctx context.Context, req *UpdateItemIntervalRequest) (*UpdateItemIntervalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItemInterval not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) InsertSource(ctx context.Context, req *InsertSourceRequest) (*InsertSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertSource not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) UpdateSource(ctx context.Context, req *UpdateSourceRequest) (*UpdateSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSource not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) UpdateSourceSet(ctx context.Context, req *UpdateSourceSetRequest) (*UpdateSourceSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSourceSet not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchSources(ctx context.Context, req *FetchSourcesRequest) (*FetchSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSources not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchSourcesPagination(ctx context.Context, req *FetchSourcesPaginationRequest) (*FetchSourcesPaginationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSourcesPagination not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) FetchSourceSet(ctx context.Context, req *FetchSourceSetRequest) (*FetchSourceSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSourceSet not implemented")
}
func (*UnimplementedHarvesterInternalApiServer) DeleteSource(ctx context.Context, req *DeleteSourceRequest) (*DeleteSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSource not implemented")
}

func RegisterHarvesterInternalApiServer(s *grpc.Server, srv HarvesterInternalApiServer) {
	s.RegisterService(&_HarvesterInternalApi_serviceDesc, srv)
}

func _HarvesterInternalApi_FetchItemUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchItemUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchItemUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchItemUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchItemUpdates(ctx, req.(*FetchItemUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchItemTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchItemTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchItemTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchItemTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchItemTypes(ctx, req.(*FetchItemTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_UpdateItemInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemIntervalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).UpdateItemInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/UpdateItemInterval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).UpdateItemInterval(ctx, req.(*UpdateItemIntervalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_InsertSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).InsertSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/InsertSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).InsertSource(ctx, req.(*InsertSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_UpdateSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).UpdateSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/UpdateSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).UpdateSource(ctx, req.(*UpdateSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_UpdateSourceSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).UpdateSourceSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/UpdateSourceSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).UpdateSourceSet(ctx, req.(*UpdateSourceSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchSources(ctx, req.(*FetchSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchSourcesPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSourcesPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchSourcesPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchSourcesPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchSourcesPagination(ctx, req.(*FetchSourcesPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_FetchSourceSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSourceSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).FetchSourceSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/FetchSourceSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).FetchSourceSet(ctx, req.(*FetchSourceSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarvesterInternalApi_DeleteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarvesterInternalApiServer).DeleteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HarvesterInternalApi/DeleteSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarvesterInternalApiServer).DeleteSource(ctx, req.(*DeleteSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HarvesterInternalApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HarvesterInternalApi",
	HandlerType: (*HarvesterInternalApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchItemUpdates",
			Handler:    _HarvesterInternalApi_FetchItemUpdates_Handler,
		},
		{
			MethodName: "FetchItemTypes",
			Handler:    _HarvesterInternalApi_FetchItemTypes_Handler,
		},
		{
			MethodName: "UpdateItemInterval",
			Handler:    _HarvesterInternalApi_UpdateItemInterval_Handler,
		},
		{
			MethodName: "InsertSource",
			Handler:    _HarvesterInternalApi_InsertSource_Handler,
		},
		{
			MethodName: "UpdateSource",
			Handler:    _HarvesterInternalApi_UpdateSource_Handler,
		},
		{
			MethodName: "UpdateSourceSet",
			Handler:    _HarvesterInternalApi_UpdateSourceSet_Handler,
		},
		{
			MethodName: "FetchSources",
			Handler:    _HarvesterInternalApi_FetchSources_Handler,
		},
		{
			MethodName: "FetchSourcesPagination",
			Handler:    _HarvesterInternalApi_FetchSourcesPagination_Handler,
		},
		{
			MethodName: "FetchSourceSet",
			Handler:    _HarvesterInternalApi_FetchSourceSet_Handler,
		},
		{
			MethodName: "DeleteSource",
			Handler:    _HarvesterInternalApi_DeleteSource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "harvesterinternalapi.proto",
}
